os: Visual Studio 2019

dotnet_csproj:
  patch: true
  file: 'src\ChessSharp\ChessSharp.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
